# Site settings
title: Hello_World()
header-img: img/home-bg.jpg
email: m.aly.ashour@gmail.com
copyright_name:
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://Mohammed-Ashour.github.io"
twitter_username:
github_username:  Mohammed-Ashour
facebook_username:
email_username:  m.aly.ashour@gmail.com
youtube_username: UCMWoyK_xNL4Ubbhoiwylhxg
linkedin_username: malyashour
# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
